[package]
name = "wth-m8"
version = "0.1.0"
authors = ["Øyvind Sigmundson Schøyen <oyvindschoyen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "=0.15.1"
sub-wth = { path = "sub-wth" }
